proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=nextjs_zone:32m inactive=7d max_size=8G use_temp_path=off;

server {
  listen 80 default_server;
  listen [::]:80 default_server;

  server_name template.com www.template.com;

  return 301 https://$main_domain$request_uri;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  http2 on;

  server_name www.template.com;

  return 301 https://$main_domain$request_uri;

  ssl_certificate /etc/letsencrypt/live/template.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/template.com/privkey.pem;
}

server {
  listen 443 ssl default_server;
  listen [::]:443 ssl default_server;
  http2 on;

  server_name template.com;

  server_tokens off;

  ssl_certificate /etc/letsencrypt/live/template.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/template.com/privkey.pem;
  include /etc/nginx/snippets/ssl-params.conf;

  gzip on;
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

  location /_next/static {
    proxy_cache nextjs_zone;
    proxy_pass http://web:3000;
    proxy_read_timeout 60;
    proxy_connect_timeout 60;

    add_header X-Cache $upstream_cache_status;
  }

  location / {
    proxy_pass http://web:3000;
    proxy_read_timeout 60;
    proxy_connect_timeout 60;
    proxy_redirect off;
    proxy_set_header GE-Original-Host $host;
  }

  location ~ /.well-known {
    allow all;
  }
}
